# This is a basic workflow to help you get started with Actions

name: ZAction

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/2 * * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #  branches: [ main ]
  # pull_request:
  #  branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        env: 
          ZZJ: zukgit

      # Runs a single command using the runners shell
      - name: Run Dynamic Stock Day Python
        run: |
         echo ___________tree_begin ___________
         tree
         echo ___________tree_end___________
         echo ___________dir_begin___________
         dir
         echo ___________dir_end___________
         echo Hello, world! 
         echo ___________java_begin___________
         java -version
         java 
         echo ___________java_end___________
         echo ___________python_begin___________
         python --version
         echo ___________python_end___________
         echo $ZZJ
         dir
         cmd
         echo day_2022_0217.json
         # cmd /K zbatrule_I9_Rule30.bat
         echo zbatrule_I9_Rule30.bat
         echo ___________PATH_begin___________
         echo ___________ PATH end___________
         echo ___________env_begin___________
         env
         echo ___________env_end___________
       
         echo USERPROFILE__Begin  $USERPROFILE
         echo ___________cmdA_end___________
         dir
         # xcopy /y   zbin\  $USERPROFILE\Desktop
      
         xcopy /y /c  /e /h /r /s zbin\*.*  C:\Users\runneradmin\Desktop\zbin\
         
         pip install tushare==1.2.84
         pip install pandas==1.4.1
         pip install openpyxl==3.0.9

         # cd C:\Users\runneradmin\Desktop
         
         # dir
         # cd C:\Users\runneradmin\Desktop\zbin
         # dir
         
         # cd C:\Users\runneradmin\Desktop\zbin\win_zbin
         # dir
         # cmd /K C:\Users\runneradmin\Desktop\zbin\win_zbin\zstock_tushare_tool_J0.bat
         cmd /K C:\Users\runneradmin\Desktop\zbin\win_zbin\zrule_apply_G2.bat

         # cmd /K $USERPROFILE\Desktop\zbin\win_zbin\zstock_tushare_tool_J0.bat
          
         echo ___________cmdB_end___________
         cmd /K C:\Users\runneradmin\Desktop\zbin\win_zbin\zstock_tushare_tool_J0.bat make_dynamic_batsh
         # cmd /K $USERPROFILE\Desktop\zbin\win_zbin\zstock_tushare_tool_J0.bat
          
         # cd $USERPROFILE\Desktop 
         dir
         
         cmd /K C:\Users\runneradmin\Desktop\zbin\J0_Dynamic_Bat.bat
         
         # C:\Users\runneradmin\Desktop\zbin\win_zbin\zstock_tushare_tool_J0.bat  day_20220224   && echo hello-zukgit  &&  C:\Users\runneradmin\Desktop\zbin\J0_DayPython\J0_0000_call_day_python.bat  20220224 && C:\Users\runneradmin\Desktop\zbin\win_zbin\zrule_apply_G2.bat _38 C:\Users\runneradmin\Desktop\zbin\J0_Data\
        
         # echo ___________win_zbin_end___________
         # cd C:\Users\runneradmin\Desktop\zbin\win_zbin
         # dir
         # echo ___________zbin_zbin_end___________

          # cd C:\Users\runneradmin\Desktop\zbin\
          # dir
          # cat  C:\Users\runneradmin\Desktop\zbin\J0_DayPython\day_20220224.py

          xcopy /y /c  /e /h /r /s C:\Users\runneradmin\Desktop\zbin\J0_Data\*.*  J0_Data\
          
          git config --global user.email "ZukGit"

          git config --global user.name "382581427@qq.com" 

          cmd /K zbatrule_I9_Rule30.bat _33_
          # git status
          # git add .
          # git commit -m "update by github actions"
          # git push 
          # git log 
           
          cd C:\Users\runneradmin\Desktop\zbin\J0_Data\
          dir
          
          # cat  C:\Users\runneradmin\Desktop\zbin\J0_Data\day_2022_0224.json
          
          # pip list
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
