# This is a basic workflow to help you get started with Actions

name: ZAction

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        env: 
          ZZJ: zukgit

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
         echo ___________tree_begin ___________
         tree
         echo ___________tree_end___________
         echo ___________dir_begin___________
         dir
         echo ___________dir_end___________
         echo Hello, world! 
         echo ___________java_begin___________
         java -version
         java 
         echo ___________java_end___________
         echo ___________python_begin___________
         python --version
         echo ___________python_end___________
         echo $ZZJ
         dir
         
         cmd
         echo day_2022_0217.json
         cmd /K zbatrule_I9_Rule30.bat
         start zbatrule_I9_Rule30.bat
         echo zbatrule_I9_Rule30.bat
         echo ___________PATH_begin___________
         echo ___________ PATH end___________
         echo ___________env_begin___________
         env
         echo ___________env_end___________
       
         echo $USERPROFILE
         echo %USERPROFILE%
         xcopy /y   zbin\  $USERPROFILE\Desktop
         cd $USERPROFILE\Desktop
         
         dir
        
         echo ___________cmdA_end___________
         cmd /K $USERPROFILE\Desktop\zbin\win_zbin\zstock_tushare_tool_J0.bat
          
         echo ___________cmdB_end___________
         cmd /K $USERPROFILE\Desktop\zbin\win_zbin\zstock_tushare_tool_J0.bat
          
    
         
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
